// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package com.example.springdemo.medicationDispenser;

public interface AllRepliesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Assignment3.AllReplies)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  java.util.List<com.example.springdemo.medicationDispenser.Reply> 
      getRepliesListList();
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  com.example.springdemo.medicationDispenser.Reply getRepliesList(int index);
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  int getRepliesListCount();
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  java.util.List<? extends com.example.springdemo.medicationDispenser.ReplyOrBuilder> 
      getRepliesListOrBuilderList();
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  com.example.springdemo.medicationDispenser.ReplyOrBuilder getRepliesListOrBuilder(
      int index);
}
