// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package com.example.springdemo.medicationDispenser;

/**
 * Protobuf type {@code Assignment3.AllReplies}
 */
public  final class AllReplies extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Assignment3.AllReplies)
    AllRepliesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllReplies.newBuilder() to construct.
  private AllReplies(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllReplies() {
    repliesList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllReplies(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              repliesList_ = new java.util.ArrayList<com.example.springdemo.medicationDispenser.Reply>();
              mutable_bitField0_ |= 0x00000001;
            }
            repliesList_.add(
                input.readMessage(com.example.springdemo.medicationDispenser.Reply.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        repliesList_ = java.util.Collections.unmodifiableList(repliesList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.springdemo.medicationDispenser.Proto.internal_static_Assignment3_AllReplies_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.springdemo.medicationDispenser.Proto.internal_static_Assignment3_AllReplies_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.springdemo.medicationDispenser.AllReplies.class, com.example.springdemo.medicationDispenser.AllReplies.Builder.class);
  }

  public static final int REPLIESLIST_FIELD_NUMBER = 1;
  private java.util.List<com.example.springdemo.medicationDispenser.Reply> repliesList_;
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  public java.util.List<com.example.springdemo.medicationDispenser.Reply> getRepliesListList() {
    return repliesList_;
  }
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  public java.util.List<? extends com.example.springdemo.medicationDispenser.ReplyOrBuilder> 
      getRepliesListOrBuilderList() {
    return repliesList_;
  }
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  public int getRepliesListCount() {
    return repliesList_.size();
  }
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  public com.example.springdemo.medicationDispenser.Reply getRepliesList(int index) {
    return repliesList_.get(index);
  }
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  public com.example.springdemo.medicationDispenser.ReplyOrBuilder getRepliesListOrBuilder(
      int index) {
    return repliesList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < repliesList_.size(); i++) {
      output.writeMessage(1, repliesList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < repliesList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, repliesList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.springdemo.medicationDispenser.AllReplies)) {
      return super.equals(obj);
    }
    com.example.springdemo.medicationDispenser.AllReplies other = (com.example.springdemo.medicationDispenser.AllReplies) obj;

    boolean result = true;
    result = result && getRepliesListList()
        .equals(other.getRepliesListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRepliesListCount() > 0) {
      hash = (37 * hash) + REPLIESLIST_FIELD_NUMBER;
      hash = (53 * hash) + getRepliesListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.springdemo.medicationDispenser.AllReplies parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.springdemo.medicationDispenser.AllReplies prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Assignment3.AllReplies}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Assignment3.AllReplies)
      com.example.springdemo.medicationDispenser.AllRepliesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.springdemo.medicationDispenser.Proto.internal_static_Assignment3_AllReplies_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.springdemo.medicationDispenser.Proto.internal_static_Assignment3_AllReplies_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.springdemo.medicationDispenser.AllReplies.class, com.example.springdemo.medicationDispenser.AllReplies.Builder.class);
    }

    // Construct using com.example.springdemo.medicationDispenser.AllReplies.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRepliesListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (repliesListBuilder_ == null) {
        repliesList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        repliesListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.springdemo.medicationDispenser.Proto.internal_static_Assignment3_AllReplies_descriptor;
    }

    @java.lang.Override
    public com.example.springdemo.medicationDispenser.AllReplies getDefaultInstanceForType() {
      return com.example.springdemo.medicationDispenser.AllReplies.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.springdemo.medicationDispenser.AllReplies build() {
      com.example.springdemo.medicationDispenser.AllReplies result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.springdemo.medicationDispenser.AllReplies buildPartial() {
      com.example.springdemo.medicationDispenser.AllReplies result = new com.example.springdemo.medicationDispenser.AllReplies(this);
      int from_bitField0_ = bitField0_;
      if (repliesListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          repliesList_ = java.util.Collections.unmodifiableList(repliesList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.repliesList_ = repliesList_;
      } else {
        result.repliesList_ = repliesListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.springdemo.medicationDispenser.AllReplies) {
        return mergeFrom((com.example.springdemo.medicationDispenser.AllReplies)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.springdemo.medicationDispenser.AllReplies other) {
      if (other == com.example.springdemo.medicationDispenser.AllReplies.getDefaultInstance()) return this;
      if (repliesListBuilder_ == null) {
        if (!other.repliesList_.isEmpty()) {
          if (repliesList_.isEmpty()) {
            repliesList_ = other.repliesList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRepliesListIsMutable();
            repliesList_.addAll(other.repliesList_);
          }
          onChanged();
        }
      } else {
        if (!other.repliesList_.isEmpty()) {
          if (repliesListBuilder_.isEmpty()) {
            repliesListBuilder_.dispose();
            repliesListBuilder_ = null;
            repliesList_ = other.repliesList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            repliesListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRepliesListFieldBuilder() : null;
          } else {
            repliesListBuilder_.addAllMessages(other.repliesList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.springdemo.medicationDispenser.AllReplies parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.springdemo.medicationDispenser.AllReplies) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.springdemo.medicationDispenser.Reply> repliesList_ =
      java.util.Collections.emptyList();
    private void ensureRepliesListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        repliesList_ = new java.util.ArrayList<com.example.springdemo.medicationDispenser.Reply>(repliesList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.springdemo.medicationDispenser.Reply, com.example.springdemo.medicationDispenser.Reply.Builder, com.example.springdemo.medicationDispenser.ReplyOrBuilder> repliesListBuilder_;

    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public java.util.List<com.example.springdemo.medicationDispenser.Reply> getRepliesListList() {
      if (repliesListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(repliesList_);
      } else {
        return repliesListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public int getRepliesListCount() {
      if (repliesListBuilder_ == null) {
        return repliesList_.size();
      } else {
        return repliesListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public com.example.springdemo.medicationDispenser.Reply getRepliesList(int index) {
      if (repliesListBuilder_ == null) {
        return repliesList_.get(index);
      } else {
        return repliesListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder setRepliesList(
        int index, com.example.springdemo.medicationDispenser.Reply value) {
      if (repliesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepliesListIsMutable();
        repliesList_.set(index, value);
        onChanged();
      } else {
        repliesListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder setRepliesList(
        int index, com.example.springdemo.medicationDispenser.Reply.Builder builderForValue) {
      if (repliesListBuilder_ == null) {
        ensureRepliesListIsMutable();
        repliesList_.set(index, builderForValue.build());
        onChanged();
      } else {
        repliesListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder addRepliesList(com.example.springdemo.medicationDispenser.Reply value) {
      if (repliesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepliesListIsMutable();
        repliesList_.add(value);
        onChanged();
      } else {
        repliesListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder addRepliesList(
        int index, com.example.springdemo.medicationDispenser.Reply value) {
      if (repliesListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepliesListIsMutable();
        repliesList_.add(index, value);
        onChanged();
      } else {
        repliesListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder addRepliesList(
        com.example.springdemo.medicationDispenser.Reply.Builder builderForValue) {
      if (repliesListBuilder_ == null) {
        ensureRepliesListIsMutable();
        repliesList_.add(builderForValue.build());
        onChanged();
      } else {
        repliesListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder addRepliesList(
        int index, com.example.springdemo.medicationDispenser.Reply.Builder builderForValue) {
      if (repliesListBuilder_ == null) {
        ensureRepliesListIsMutable();
        repliesList_.add(index, builderForValue.build());
        onChanged();
      } else {
        repliesListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder addAllRepliesList(
        java.lang.Iterable<? extends com.example.springdemo.medicationDispenser.Reply> values) {
      if (repliesListBuilder_ == null) {
        ensureRepliesListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, repliesList_);
        onChanged();
      } else {
        repliesListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder clearRepliesList() {
      if (repliesListBuilder_ == null) {
        repliesList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        repliesListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public Builder removeRepliesList(int index) {
      if (repliesListBuilder_ == null) {
        ensureRepliesListIsMutable();
        repliesList_.remove(index);
        onChanged();
      } else {
        repliesListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public com.example.springdemo.medicationDispenser.Reply.Builder getRepliesListBuilder(
        int index) {
      return getRepliesListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public com.example.springdemo.medicationDispenser.ReplyOrBuilder getRepliesListOrBuilder(
        int index) {
      if (repliesListBuilder_ == null) {
        return repliesList_.get(index);  } else {
        return repliesListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public java.util.List<? extends com.example.springdemo.medicationDispenser.ReplyOrBuilder> 
         getRepliesListOrBuilderList() {
      if (repliesListBuilder_ != null) {
        return repliesListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(repliesList_);
      }
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public com.example.springdemo.medicationDispenser.Reply.Builder addRepliesListBuilder() {
      return getRepliesListFieldBuilder().addBuilder(
          com.example.springdemo.medicationDispenser.Reply.getDefaultInstance());
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public com.example.springdemo.medicationDispenser.Reply.Builder addRepliesListBuilder(
        int index) {
      return getRepliesListFieldBuilder().addBuilder(
          index, com.example.springdemo.medicationDispenser.Reply.getDefaultInstance());
    }
    /**
     * <code>repeated .Assignment3.Reply repliesList = 1;</code>
     */
    public java.util.List<com.example.springdemo.medicationDispenser.Reply.Builder> 
         getRepliesListBuilderList() {
      return getRepliesListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.springdemo.medicationDispenser.Reply, com.example.springdemo.medicationDispenser.Reply.Builder, com.example.springdemo.medicationDispenser.ReplyOrBuilder> 
        getRepliesListFieldBuilder() {
      if (repliesListBuilder_ == null) {
        repliesListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.springdemo.medicationDispenser.Reply, com.example.springdemo.medicationDispenser.Reply.Builder, com.example.springdemo.medicationDispenser.ReplyOrBuilder>(
                repliesList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        repliesList_ = null;
      }
      return repliesListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Assignment3.AllReplies)
  }

  // @@protoc_insertion_point(class_scope:Assignment3.AllReplies)
  private static final com.example.springdemo.medicationDispenser.AllReplies DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.springdemo.medicationDispenser.AllReplies();
  }

  public static com.example.springdemo.medicationDispenser.AllReplies getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AllReplies>
      PARSER = new com.google.protobuf.AbstractParser<AllReplies>() {
    @java.lang.Override
    public AllReplies parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AllReplies(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AllReplies> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AllReplies> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.springdemo.medicationDispenser.AllReplies getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

