// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package com.example.springdemo.medicationDispenser;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Assignment3_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Assignment3_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Assignment3_Reply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Assignment3_Reply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Assignment3_AllReplies_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Assignment3_AllReplies_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013proto.proto\022\013Assignment3\"\027\n\007Request\022\014\n" +
      "\004date\030\001 \001(\t\"y\n\005Reply\022\014\n\004name\030\001 \001(\t\022\026\n\016me" +
      "dicationName\030\002 \001(\t\022\021\n\tstartDate\030\003 \001(\t\022\017\n" +
      "\007endDate\030\004 \001(\t\022\016\n\006dosage\030\005 \001(\t\022\026\n\016intake" +
      "Interval\030\006 \001(\t\"5\n\nAllReplies\022\'\n\013repliesL" +
      "ist\030\001 \003(\0132\022.Assignment3.Reply2\323\001\n\007Greete" +
      "r\022;\n\010SayHello\022\024.Assignment3.Request\032\027.As" +
      "signment3.AllReplies\"\000\022C\n\020transmitRespon" +
      "se\022\027.Assignment3.AllReplies\032\024.Assignment" +
      "3.Request\"\000\022F\n\030transmitPositiveResponse\022" +
      "\022.Assignment3.Reply\032\024.Assignment3.Reques" +
      "t\"\000B;\n*com.example.springdemo.medication" +
      "DispenserB\005ProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Assignment3_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Assignment3_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Assignment3_Request_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_Assignment3_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Assignment3_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Assignment3_Reply_descriptor,
        new java.lang.String[] { "Name", "MedicationName", "StartDate", "EndDate", "Dosage", "IntakeInterval", });
    internal_static_Assignment3_AllReplies_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Assignment3_AllReplies_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Assignment3_AllReplies_descriptor,
        new java.lang.String[] { "RepliesList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
