// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package com.sd.Assignment3;

public interface AllRepliesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Assignment3.AllReplies)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  java.util.List<com.sd.Assignment3.Reply> 
      getRepliesListList();
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  com.sd.Assignment3.Reply getRepliesList(int index);
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  int getRepliesListCount();
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  java.util.List<? extends com.sd.Assignment3.ReplyOrBuilder> 
      getRepliesListOrBuilderList();
  /**
   * <code>repeated .Assignment3.Reply repliesList = 1;</code>
   */
  com.sd.Assignment3.ReplyOrBuilder getRepliesListOrBuilder(
      int index);
}
