// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package com.sd.Assignment3;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Assignment3.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string medicationName = 2;</code>
   */
  java.lang.String getMedicationName();
  /**
   * <code>string medicationName = 2;</code>
   */
  com.google.protobuf.ByteString
      getMedicationNameBytes();

  /**
   * <code>string startDate = 3;</code>
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string endDate = 4;</code>
   */
  java.lang.String getEndDate();
  /**
   * <code>string endDate = 4;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();

  /**
   * <code>string dosage = 5;</code>
   */
  java.lang.String getDosage();
  /**
   * <code>string dosage = 5;</code>
   */
  com.google.protobuf.ByteString
      getDosageBytes();

  /**
   * <code>string intakeInterval = 6;</code>
   */
  java.lang.String getIntakeInterval();
  /**
   * <code>string intakeInterval = 6;</code>
   */
  com.google.protobuf.ByteString
      getIntakeIntervalBytes();
}
