// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package com.sd.Assignment3;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Assignment3.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
