
package com.sd.assignment4.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DoctorServiceImpl", targetNamespace = "http://services.assignment4.sd.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DoctorServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sd.assignment4.services.MapDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMap", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.GetMap")
    @ResponseWrapper(localName = "getMapResponse", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.GetMapResponse")
    @Action(input = "http://services.assignment4.sd.com/DoctorServiceImpl/getMapRequest", output = "http://services.assignment4.sd.com/DoctorServiceImpl/getMapResponse")
    public MapDTO getMap(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sd.assignment4.services.ActivityDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllActivities", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.GetAllActivities")
    @ResponseWrapper(localName = "getAllActivitiesResponse", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.GetAllActivitiesResponse")
    @Action(input = "http://services.assignment4.sd.com/DoctorServiceImpl/getAllActivitiesRequest", output = "http://services.assignment4.sd.com/DoctorServiceImpl/getAllActivitiesResponse")
    public List<ActivityDTO> getAllActivities(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveActivity", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.SaveActivity")
    @ResponseWrapper(localName = "saveActivityResponse", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.SaveActivityResponse")
    @Action(input = "http://services.assignment4.sd.com/DoctorServiceImpl/saveActivityRequest", output = "http://services.assignment4.sd.com/DoctorServiceImpl/saveActivityResponse")
    public void saveActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sd.assignment4.services.PillDispenserDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPillDispenser", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.GetAllPillDispenser")
    @ResponseWrapper(localName = "getAllPillDispenserResponse", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.GetAllPillDispenserResponse")
    @Action(input = "http://services.assignment4.sd.com/DoctorServiceImpl/getAllPillDispenserRequest", output = "http://services.assignment4.sd.com/DoctorServiceImpl/getAllPillDispenserResponse")
    public List<PillDispenserDTO> getAllPillDispenser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveRecommendation", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.SaveRecommendation")
    @ResponseWrapper(localName = "saveRecommendationResponse", targetNamespace = "http://services.assignment4.sd.com/", className = "com.sd.assignment4.services.SaveRecommendationResponse")
    @Action(input = "http://services.assignment4.sd.com/DoctorServiceImpl/saveRecommendationRequest", output = "http://services.assignment4.sd.com/DoctorServiceImpl/saveRecommendationResponse")
    public void saveRecommendation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
