
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Caregiver", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:51111/Caregiver.asmx?wsdl")
public class Caregiver
    extends Service
{

    private final static URL CAREGIVER_WSDL_LOCATION;
    private final static WebServiceException CAREGIVER_EXCEPTION;
    private final static QName CAREGIVER_QNAME = new QName("http://tempuri.org/", "Caregiver");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:51111/Caregiver.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAREGIVER_WSDL_LOCATION = url;
        CAREGIVER_EXCEPTION = e;
    }

    public Caregiver() {
        super(__getWsdlLocation(), CAREGIVER_QNAME);
    }

    public Caregiver(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAREGIVER_QNAME, features);
    }

    public Caregiver(URL wsdlLocation) {
        super(wsdlLocation, CAREGIVER_QNAME);
    }

    public Caregiver(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAREGIVER_QNAME, features);
    }

    public Caregiver(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Caregiver(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CaregiverSoap
     */
    @WebEndpoint(name = "CaregiverSoap")
    public CaregiverSoap getCaregiverSoap() {
        return super.getPort(new QName("http://tempuri.org/", "CaregiverSoap"), CaregiverSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaregiverSoap
     */
    @WebEndpoint(name = "CaregiverSoap")
    public CaregiverSoap getCaregiverSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CaregiverSoap"), CaregiverSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAREGIVER_EXCEPTION!= null) {
            throw CAREGIVER_EXCEPTION;
        }
        return CAREGIVER_WSDL_LOCATION;
    }

}
